# Generated by Django 5.2.11 on 2026-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("italian", "Italian"),
                            ("chinese", "Chinese"),
                            ("indian", "Indian"),
                            ("mexican", "Mexican"),
                            ("japanese", "Japanese"),
                            ("french", "French"),
                            ("american", "American"),
                            ("thai", "Thai"),
                            ("korean", "Korean"),
                            ("vietnamese", "Vietnamese"),
                            ("turkish", "Turkish"),
                            ("seafood", "Seafood"),
                            ("vegan", "Vegan"),
                            ("fusion", "Fusion"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("logo", models.ImageField(blank=True, upload_to="restaurant_logos/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="restaurant_covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.CharField(max_length=10)),
                ("capacity", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["table_number"],
            },
        ),
    ]
