# Generated by Django 5.2.11 on 2026-02-16 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_reservation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
