# Generated by Django 5.2.11 on 2026-02-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_delete_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(
                default=1,
                help_text="URL-friendly identifier for the restaurant",
                max_length=200,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
